version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-kasir
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kasir
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-kasir
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: pass
    ports:
      - "8082:80"

  php:
    image: php:8.1-apache
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-belajar
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

volumes:
  mysql-data:
